name: Homebridge
version: 0.1.7
stage: experimental
slug: homebridge
description: Lightweight HomeKit API implementation with plugin support
arch:
  - armv7
  - aarch64
  - amd64
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
webui: http://[HOST]:[PORT:8581]
host_network: true
init: false
map:
  - config:rw
options:
  homebridge_workdir: "/config/homebridge"
schema:
  homebridge_workdir: str
image: davide125/{arch}-addon-homebridge
